### PR TITLE
add test should wait for selectors with delay

### PR DESCRIPTION
**Pull request by Oberuks**

### CODE REVIEW

**Comment by amaitland** [comment]
Does the new test fail when you run it locally? Looks like the unit test ran successfully as part of https://ci.appveyor.com/project/cefsharp/cefsharp-dom/builds/45366995

**Comment by amaitland** [comment]
There are instructions for creating the certificate in the contributing guide.

https://github.com/cefsharp/CefSharp.Dom/blob/main/CONTRIBUTING.md#getting-setup

**Comment by Oberuks** [comment]
I repeated the steps according to your instructions but could not generate a certificate. In the script, I specified my path for the certificate.

**Comment by Oberuks** [comment]
I repeated the steps according to your instructions but could not generate a certificate. In the script, I specified my path for the certificate.
```
New-SelfSignedCertificate -Subject "localhost" -FriendlyName "Puppeteer" -CertStoreLocation "cert:\CurrentUser\My"
Get-ChildItem -Path cert:\CurrentUSer\my | where { $_.friendlyname -eq "Puppeteer" } | Export-Certificate -FilePath D:\Projects\C#\Browser\CefSharp.Dom\lib\PuppeteerSharp.TestServer\testCert.cer
```
As a result I get еру error
```
PS D:\2> .\sert.ps1


   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\My

Thumbprint                                Subject
----------                                -------
19789A42CCE9409AAF13AF2DD73753F3D8CDA9D2  CN=localhost
Export-Certificate : Недопустимый тип. Входной объект имеет более одного сертификата.
D:\2\sert.ps1:3 знак:88
+ ... peteer" } | Export-Certificate -FilePath D:\Projects\C#\Browser\CefSh ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Export-Certificate], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.CertificateServices.Commands.ExportCertif
   icateCommand
```
Can you try running my simple solution yourself? It could save a lot of time for both of us.

**Comment by amaitland** [comment]
> Can you try running my simple solution yourself? It could save a lot of time for both of us.

A unit test is required to debug the issue.

**Comment by amaitland** [comment]
The CI builds generate the certificate as part of the build process, another example is https://github.com/cefsharp/CefSharp.Dom/blob/main/appveyor.yml#L15

**Comment by Oberuks** [comment]
I made a mistake in testing product versions. There is no problem in the current repository at github.com CefSharp.Dom. The problem I described is in the nugget build 2.0.83 dated 9/12/2022. This PR needs to be closed.

**Pull request closed without merging**
